name: Test App

on: [ pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get swift version
        run: swift --version

      - name: Install mise
        run: curl https://mise.run | sh

      - name: Check mise version
        run: ~/.local/bin/mise --version

      - name: Activate mise
        run: ~/.local/bin/mise activate

      - name: Install Tuist
        run: mise install tuist

      - name: Install app dependencies
        run: tuist install

      - name: Run tests
        run: tuist test 'WhyNotSwiftUI Development' --skip-test-targets NetworkKitTests/NetworkProdTests