name: Test App

on: [ pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Get swift version
        run: swift --version

      - name: Install app dependencies
        run: tuist install

      - name: Run tests
        run: tuist test 'WhyNotSwiftUI Development' --skip-test-targets NetworkKitTests/NetworkProdTests