name: Test App

on: [ pull_request ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.3"

      - name: Get swift version
        run: swift --version

      - name: Get swift version in macOS
        if: runner.os == 'macOS'
        run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version

      - name: Installed simulators
        run: xcrun simctl list

      - name: Install app dependencies
        run: tuist install

      - name: Run tests
        run: tuist test 'WhyNotSwiftUI Development' --skip-test-targets NetworkKitTests/NetworkProdTests